---
- name: Install dokuwiki
  # hosts: learn.delaporte.us
  hosts: vagrant
  # remote_user: vagrant
  user: vagrant
  sudo: yes
  gather_facts: false
  
  roles:
   - debian-fixes
   - { role: nginx, configuration_file: 'roles/dokuwiki/templates/default.conf', dest: dokuwiki }
   - php5-fpm
   - dokuwiki
